// const macroTable = [
// 'calories',
// 'totalFat',
// 'saturatedFat',
// 'unsaturatedFat',
// 'transFat',
// 'cholesterol',
// 'totalCarbs',
// 'dietaryFiber',
// 'totalSugars',
// 'proteins',
// ];

// saturatedFat,
//     unsaturatedFat,
//     transFat,
//     cholesterol,
//     totalCarbs,
//     dietaryFiber,
//     totalSugars,
//     proteins,
//     // sodium,
//     // iron,
//     // potassium,
//     // calcium,
//     // zinc,
//     // vitaminA,
//     // vitaminB6,
//     // vitaminB12,
//     // vitaminC,
//     // vitaminD,
//     // vitaminE,
//     // vitaminK,
